# ═══════════════════════════════════════════════════════════════
#  ayesha-os cloud model setup
#  run:  .\scripts\setup-cloud.ps1
# ═══════════════════════════════════════════════════════════════

$envFile = Join-Path $PSScriptRoot ".." ".env"

Write-Host ""
Write-Host "  ╔══════════════════════════════════════════════╗" -ForegroundColor Cyan
Write-Host "  ║   ayesha-os cloud model setup   (◕‿◕✿)      ║" -ForegroundColor Cyan
Write-Host "  ╚══════════════════════════════════════════════╝" -ForegroundColor Cyan
Write-Host ""
Write-Host "  this will set up free cloud AI models, desu~" -ForegroundColor Green
Write-Host ""

# ── load existing .env if present ──
$existing = @{}
if (Test-Path $envFile) {
    Get-Content $envFile | ForEach-Object {
        if ($_ -match '^([A-Z_]+)=(.+)$') {
            $existing[$Matches[1]] = $Matches[2]
        }
    }
}

# ── provider menu ──
Write-Host "  which provider do you want to set up?" -ForegroundColor Yellow
Write-Host ""
Write-Host "  [1] kilo gateway  (kilo-auto/free, kilo, kilo, kilo — all FREE)" -ForegroundColor White
Write-Host ""
$choice = Read-Host "  enter 1"

$dokilo gateway = $choice -eq "1"

$envLines = @()

# ── openrouter setup ──
if ($dokilo gateway) {
    Write-Host ""
    Write-Host "  ── openrouter setup ──" -ForegroundColor Cyan
    Write-Host ""

    if ($existing.ContainsKey("OPENROUTER_API_KEY")) {
        $masked = $existing["OPENROUTER_API_KEY"].Substring(0, [Math]::Min(12, $existing["OPENROUTER_API_KEY"].Length)) + "..."
        Write-Host "  existing key found: $masked" -ForegroundColor DarkGray
        $reuse = Read-Host "  keep it? (y/n)"
        if ($reuse -eq "y" -or $reuse -eq "Y" -or $reuse -eq "") {
            $envLines += "OPENROUTER_API_KEY=$($existing['OPENROUTER_API_KEY'])"
            Write-Host "  ✔ kept existing key" -ForegroundColor Green
            $dokilo gateway = $false
        }
    }

    if ($dokilo gateway) {
        Write-Host "  1. go to: https://openrouter.ai/keys" -ForegroundColor White
        Write-Host "  2. sign up (free) or log in" -ForegroundColor White
        Write-Host "  3. create a new API key" -ForegroundColor White
        Write-Host "  4. paste it below" -ForegroundColor White
        Write-Host ""
        Start-Process "https://openrouter.ai/keys"
        Write-Host "  (opened browser for you)" -ForegroundColor DarkGray
        Write-Host ""
        $orKey = Read-Host "  paste your kilo gateway API key"
        $orKey = $orKey.Trim()
        if ($orKey -ne "") {
            $envLines += "OPENROUTER_API_KEY=$orKey"
            Write-Host "  ✔ openrouter key saved" -ForegroundColor Green
        } else {
            Write-Host "  ✘ skipped (no key entered)" -ForegroundColor Red
        }
    }
}



# ── preserve any other existing env vars ──
if (Test-Path $envFile) {
    Get-Content $envFile | ForEach-Object {
        if ($_ -match '^([A-Z_]+)=') {
            $key = $Matches[1]
            if ($key -ne "OPENROUTER_API_KEY") {
                $envLines += $_
            }
        }
    }
}

# ── write .env ──
if ($envLines.Count -gt 0) {
    $header = "# ayesha-os cloud config — auto-generated by setup-cloud.ps1"
    $content = @($header) + $envLines
    $content | Set-Content -Path $envFile -Encoding UTF8
    Write-Host ""
    Write-Host "  ✔ saved to .env" -ForegroundColor Green
}

# ── summary ──
Write-Host ""
Write-Host "  ═══════════════════════════════════════════════" -ForegroundColor Cyan
Write-Host "  setup complete! available free cloud models:" -ForegroundColor Green
Write-Host ""

if ($envLines -match "OPENROUTER_API_KEY") {
    Write-Host "  openrouter (free tier):" -ForegroundColor Yellow
    Write-Host "    • nvidia/kilo-auto/free:free   (120B MoE, 1M context)" -ForegroundColor White
    Write-Host "    • meta-llama/kilo:free   (70B instruct)" -ForegroundColor White
    Write-Host "    • deepseek/kilo:free       (reasoning/thinking)" -ForegroundColor White
    Write-Host "    • qwen/qwen-2.5-coder-32b:free    (coding specialist)" -ForegroundColor White
    Write-Host ""
}



Write-Host "  to use in ayesha engine:" -ForegroundColor Cyan
Write-Host "    /model nvidia/kilo-auto/free:free" -ForegroundColor White
Write-Host "    /models                              (list all)" -ForegroundColor DarkGray
Write-Host ""
Write-Host "  kapoo! you're all set (◕ᴗ◕✿)" -ForegroundColor Magenta
Write-Host ""
